version: '3.8'

services:
  odoo-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ODOO_URL=${ODOO_URL:-https://demo.odoo.com}
      - ODOO_DATABASE=${ODOO_DATABASE:-demo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD:-admin}
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import odoo_mcp_server; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s